hostname:
  mongo: localhost
  kafka: localhost

spring:
  data:
    mongodb:
      uri: mongodb://${hostname.mongo}:27017/demo

  kafka:
    bootstrap-servers: ${hostname.kafka}:9093
    listener:
      concurrency: 3
    producer:
      batch-size: 1000
    consumer:
      group-id: myGroup1
    template:
      default-topic: iot